### ISSUE TITLE
4.x Helidon MP FaultTolerance fails In HelidonTest

### ISSUE THREAD

**Issue by tejo93** [helidon-io/helidon#8700] opened 2024-04-25 04:54 UTC
## Environment Details
* Helidon Version: 4.0.5
*  Helidon MP
* JDK version: 21
* OS: OL- 8 Linux
* Docker version (if applicable): N/A

----------

### I have this following configuration in src/main/resources/application.yaml

```java
# Application properties. This is the default greeting
# Application properties. This is the default greeting
app:
  greeting: Hello
  someClient:
    baseUrl: http://someUrl
counter: 0

  # Microprofile server properties
server:
  port: 8080
  host: 0.0.0.0

io.helidon.examples.quickstart.mp.SomeClient/Retry/enabled: true
io.helidon.examples.quickstart.mp.SomeClient/Timeout/enabled: true
io.helidon.examples.quickstart.mp.SomeClient/Retry/maxRetries: 2
io.helidon.examples.quickstart.mp.SomeClient/Timeout/value: 5000

#Rest Client Properties for Some Client Service
someClient/mp-rest/url: "${app.someClient.baseUrl}"
someClient/mp-rest/connectTimeout: 5000
someClient/mp-rest/responseTimeout: 5000
someClient/mp-rest/propagateHeaders: Accept-Language
```

### Class SomeClient is annotated like this :

```java
@RegisterRestClient(configKey = "someClient")
@Retry
@Timeout
@Asynchronous
public interface SomeClient {
   
}
```

### Method get :

```java
 @GET
    @Produces("application/json")
    @Path("/somepath")
    CompletableFuture<Response> get();
```

### Class SomeClientImpl has following changes

```java
@RequestScoped
public class SomeClientImpl implements SomeClient {

    @Override
    public CompletableFuture<Response> get() {
        return CompletableFuture.completedFuture(Response.ok("Got").build());
    }
}
```

### Class SomeClientService has following changes

```java
@ApplicationScoped
public class SomeClientService {

    private final SomeClient someClient;
    @Inject
    public SomeClientService(@RestClient SomeClient someClient) {
        this.someClient = someClient;
    }

    public CompletableFuture<Response> get() {
        return someClient.get();
    }
}
```

### I have test/resources/application.yaml

```java
config_ordinal: 200
io.helidon.examples.quickstart.mp.SomeClient/Retry/enabled: false
io.helidon.examples.quickstart.mp.SomeClient/Timeout/enabled: false
```

### Class MainTest

```java

@HelidonTest
@AddConfig(key = "someClient/mp-rest/url", value = "http://localhost:9999")
@HoverflyCore(config = @HoverflyConfig(webServer = true, proxyPort = 9999))
@ExtendWith(HoverflyExtension.class)
class MainTest {

    @Inject
    private WebTarget target;

    @Inject
    @RestClient
    SomeClient someClient;

    @Test
    void testHelloWorld()  {
        CompletableFuture<Response> response = someClient.get();
        ExecutionException exception = assertThrows(ExecutionException.class, response::get);
        assertEquals(TimeoutException.class, exception.getCause().getClass());

    }
}
```

#### When I execute the MainTest , it passes which should not happen as there is no delay set in the simulation.

[helidon-quickstart-mp (1).zip](https://github.com/helidon-io/helidon/files/15104356/helidon-quickstart-mp.1.zip)

**Comment by tomas-langer** [comment] 2024-04-25 13:20
Seems to be related to #8478

**Comment by tomas-langer** [comment] 2024-04-25 13:24
Fixes should be in 4.0.7 (resetting FT cache).
Also the recommendation was to use `config_ordinal: 500` for `application.yaml`, as 200 still conflicts with built-in config sources.

**Comment by tomas-langer** [comment] 2024-04-25 15:41
Attaching a diff that make the test fail as expected due to timeout.
I have remove completable future, as with Virtual threads, that is no longer needed.

**Comment by tomas-langer** [comment] 2024-04-25 15:42
[Changes_to_show_timeout_in_test_.patch](https://github.com/helidon-io/helidon/files/15112521/Changes_to_show_timeout_in_test_.patch)

**Comment by tomas-langer** [comment] 2024-07-23 14:45
As I have provided a working application, and I did not find a bug in our code, I am closing this issue.
Please if you have new discovery/reproducer that shows that this is not working, re-open this issue.
Thank you.

**Closed by tomas-langer** 2024-07-23 14:45 UTC
Labels: triage
