### ISSUE TITLE
HOCON substitution support broken since 2.5.0

### ISSUE THREAD

**Issue by OOPMan** [helidon-io/helidon#5871] opened 2023-01-16 17:05 UTC
[//]: # "Please remove these comments"
[//]: # "Provide a general summary of the issue in the Title above"

## Environment Details
* Helidon Version: Since 2.5.0
* Helidon SE
* JDK version: Eclipse Temurin 17.0.1_12
* OS: Kubuntu Linux 22.10
* Docker version (if applicable): N/A

----------

## Problem Description
After waiting for a while I noticed no one has filed a bug about this or fixed it. Basically, support for HOCON substitution seems to be disabled by default and it is not possible to re-enable it from what I can tell.

After running into this issue with my own code I looked through the source and discovered that:

1. `HoconConfigParserBuilder` disables substitution by default
2. `HoconConfigParserBuilder` does not provide a `create` method

As such, the example from the documentation https://helidon.io/docs/v3/#/se/config/supported-formats is not valid:

```java
Config config = Config.builder(classpath("application.conf"))
        .disableParserServices()
        .addParser(HoconConfigParserBuilder.create()              
                           .disableResolving()                    
                           .build())                              
        .build();
```

This code is invalid because there is no `create` method and thus the user can not create a custom `HoconConfigParserBuilder`. Furthermore, the class is private and final so there is no way to instantiate it via `new` from user-code.

Additionally, substitution is disabled by default and there is not method to enable it

## Steps to reproduce

1.  Use an `application.conf` HOCON file like:
```hocon
// Server config elements go here
some_variable = "my string"
some_variable = "${?SOME_VARIABLE}
```
2. Run application, attempt to make use of `some_variable`

**Comment by klustria** [comment] 2023-01-24 07:56
PR https://github.com/helidon-io/helidon/pull/4003 adds a new method [resolvingEnabled(boolean)](ttps://helidon.io/docs/v2/apidocs/io.helidon.config.hocon/io/helidon/config/hocon/HoconConfigParserBuilder.html#resolvingEnabled(boolean)) that enables/disables HOCON resolving substitutions support. Also, the doc is pretty outdated and there is no more capability to instantiate `HoconConfigParserBuilder` from itself. Rather, you can use `HoconConfigParser`. So for your purpose of enabling HOCON substitution, you can try this code instead: 

```java
        Config config = Config.builder(ConfigSources.classpath("application.conf"))
                .disableParserServices()
                .addParser(HoconConfigParser.builder().
                                   resolvingEnabled(true).
                                   build())
                .build();
```

*Note*: See the new format for creating the HoconConfigParser inside of `addParser`.

I've tested this and looks like it is working as intended. Let me know if it works from your end so we can update/correct the docs.

**Comment by klustria** [comment] 2023-01-24 08:14
BTW, [resolvingEnabled(boolean)](https://helidon.io/docs/v2/apidocs/io.helidon.config.hocon/io/helidon/config/hocon/HoconConfigParserBuilder.html#resolvingEnabled(boolean)) was added in Helidon v2.5.1 but I would suggest that you use the latest v2.5.6.

**Comment by OOPMan** [comment] 2023-01-24 13:07
@klustria Thanks!

**Comment by klustria** [comment] 2023-01-24 23:50
Reopening as the doc need to be updated with the correct commands to use.

**Comment by klustria** [comment] 2023-01-25 04:50
Doc update will be made via PR https://github.com/helidon-io/helidon/pull/5958

**Comment by klustria** [comment] 2023-01-26 16:53
Main PR https://github.com/helidon-io/helidon/pull/5958 is merged hence closing this issue.

**Closed by klustria** 2023-01-26 16:53 UTC
Labels: docs, 2.x
