### ISSUE TITLE
Websocket not closed correctly on java.net.SocketException: Connection reset

### ISSUE THREAD

**Issue by Neoministein** [helidon-io/helidon#7703] opened 2023-10-02 20:57 UTC
[//]: # "Please remove these comments"
[//]: # "Provide a general summary of the issue in the Title above"

## Environment Details
* Helidon Version: 4.0.0-RC1
* Helidon MP
* JDK version: 21
* OS: Win 10
* Docker version (if applicable): -

----------

## Problem Description

I am not quite sure if this belongs here or on in the [tyrus](https://github.com/eclipse-ee4j/tyrus) GitHub.

**Setup:**

I've got a websocket endpoint that I've registered with the `@ServerEndpoint` annoation. I've also got a method annotated with `@OnClose`.

When the websocket client crashes very hard it produces: 
```java
java.io.UncheckedIOException: java.net.SocketException: Connection reset
	at io.helidon.common.socket.PlainSocket.get(PlainSocket.java:150)
	at io.helidon.common.socket.PlainSocket.get(PlainSocket.java:32)
	at io.helidon.common.buffers.DataReader.pullData(DataReader.java:81)
	at io.helidon.common.buffers.DataReader.ensureAvailable(DataReader.java:111)
	at io.helidon.common.buffers.DataReader.readBuffer(DataReader.java:187)
	at io.helidon.microprofile.tyrus.TyrusConnection.handle(TyrusConnection.java:78)
	at io.helidon.webserver.http1.Http1Connection.handle(Http1Connection.java:160)
	at io.helidon.webserver.ConnectionHandler.run(ConnectionHandler.java:113)
	at io.helidon.common.task.InterruptableTask.call(InterruptableTask.java:47)
	at io.helidon.webserver.ThreadPerTaskExecutor$ThreadBoundFuture.run(ThreadPerTaskExecutor.java:239)
	at java.base/java.lang.VirtualThread.run(VirtualThread.java:311)
Caused by: java.net.SocketException: Connection reset
	at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:318)
	at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:346)
	at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:796)
	at java.base/java.net.Socket$SocketInputStream.read(Socket.java:1099)
	at io.helidon.common.socket.IdleInputStream.read(IdleInputStream.java:74)
	at java.base/java.io.InputStream.read(InputStream.java:220)
	at io.helidon.common.socket.PlainSocket.get(PlainSocket.java:142)
	... 10 more
```
The exception is caught and handled by `io.helidon.microprofile.tyrus.TyrusConnection.TyrusListener.onError()`. The onError method then calls `this.connection.close(...)` which then further down calls `org.glassfish.tyrus.core.ProtocolHandler.close`:

```java
    public synchronized Future<Frame> close(final int code, final String reason) {

        ...

        final Future<Frame> send = send(outgoingCloseFrame, null, CLOSE, false); //<-- Throws exception

        webSocket.onClose(new CloseFrame(closeReason));

        return send;
    }
```

The `close` method then tries so send a closing frame back to the client but since a connection does no longer exists this exception is thrown and the `@OnClose` annotated method is never called: 
```java
java.io.UncheckedIOException: java.net.SocketException: Connection reset by peer
	at io.helidon.common.buffers.FixedBufferData.writeTo(FixedBufferData.java:74) ~[helidon-common-buffers-4.0.0-RC1.jar:4.0.0-RC1]
	at io.helidon.common.socket.PlainSocket.write(PlainSocket.java:136) ~[helidon-common-socket-4.0.0-RC1.jar:4.0.0-RC1]
	at io.helidon.common.socket.SocketWriter.writeNow(SocketWriter.java:77) ~[helidon-common-socket-4.0.0-RC1.jar:4.0.0-RC1]
	at io.helidon.microprofile.tyrus.TyrusConnection$TyrusListener$1.write(TyrusConnection.java:193) ~[helidon-microprofile-websocket-4.0.0-RC1.jar:4.0.0-RC1]
	at org.glassfish.tyrus.spi.Writer.write(Writer.java:62) ~[tyrus-spi-2.0.4.jar:?]
	at org.glassfish.tyrus.core.ProtocolHandler.write(ProtocolHandler.java:496) ~[tyrus-core-2.0.4.jar:?]
	at org.glassfish.tyrus.core.ProtocolHandler.send(ProtocolHandler.java:251) ~[tyrus-core-2.0.4.jar:?]
	at org.glassfish.tyrus.core.ProtocolHandler.close(ProtocolHandler.java:479) ~[tyrus-core-2.0.4.jar:?]
	at org.glassfish.tyrus.core.TyrusWebSocket.close(TyrusWebSocket.java:244) ~[tyrus-core-2.0.4.jar:?]
	at org.glassfish.tyrus.core.TyrusWebSocketEngine$TyrusConnection.close(TyrusWebSocketEngine.java:825) ~[tyrus-core-2.0.4.jar:?]
	at io.helidon.microprofile.tyrus.TyrusConnection$TyrusListener.onError(TyrusConnection.java:179) ~[helidon-microprofile-websocket-4.0.0-RC1.jar:4.0.0-RC1]
	at io.helidon.microprofile.tyrus.TyrusConnection.handle(TyrusConnection.java:84) ~[helidon-microprofile-websocket-4.0.0-RC1.jar:4.0.0-RC1]
	at io.helidon.webserver.http1.Http1Connection.handle(Http1Connection.java:160) ~[helidon-webserver-4.0.0-RC1.jar:4.0.0-RC1]
	at io.helidon.webserver.ConnectionHandler.run(ConnectionHandler.java:113) ~[helidon-webserver-4.0.0-RC1.jar:4.0.0-RC1]
	at io.helidon.common.task.InterruptableTask.call(InterruptableTask.java:47) ~[helidon-common-task-4.0.0-RC1.jar:4.0.0-RC1]
	at io.helidon.webserver.ThreadPerTaskExecutor$ThreadBoundFuture.run(ThreadPerTaskExecutor.java:239) ~[helidon-webserver-4.0.0-RC1.jar:4.0.0-RC1]
	at java.lang.VirtualThread.run(VirtualThread.java:311) ~[?:?]
Caused by: java.net.SocketException: Connection reset by peer
	at sun.nio.ch.SocketDispatcher.write0(Native Method) ~[?:?]
	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:54) ~[?:?]
	at sun.nio.ch.NioSocketImpl.tryWrite(NioSocketImpl.java:394) ~[?:?]
	at sun.nio.ch.NioSocketImpl.implWrite(NioSocketImpl.java:410) ~[?:?]
	at sun.nio.ch.NioSocketImpl.write(NioSocketImpl.java:440) ~[?:?]
	at sun.nio.ch.NioSocketImpl$2.write(NioSocketImpl.java:819) ~[?:?]
	at java.net.Socket$SocketOutputStream.write(Socket.java:1195) ~[?:?]
	at io.helidon.common.buffers.FixedBufferData.writeTo(FixedBufferData.java:71) ~[helidon-common-buffers-4.0.0-RC1.jar:4.0.0-RC1]
	... 16 more
```

## Steps to reproduce
[//]: # "Step by step instructions to reproduce the problem"
[//]: # "Provide sample code/application if relevant"

I haven't found out a way how to produce the connection reset error in Helidon in a standalone fashion reliably. Having a websocket client and terminating the process or the operating system does not reliably produce the connection reset error.

How I came across the issue was when using a websocket written in rust which was attached to a modified videogame client ([the client](https://github.com/Neoministein/R2Northstar-Websocket)). When closing the game with a still open connection a connection reset error always is thrown. 

Java code:

```java
@ServerEndpoint(value = "/websocket/{id}")
public class WebsocketEndpoint {

    protected Map<String, List<String>> messageMap = new HashMap<>();

    @OnOpen
    public void onOpen(@PathParam("id") String id, Session session) {
        messageMap.put(id, new ArrayList<>());
    }

    @OnClose
    public void onclose(@PathParam("id") String id) {
        messageMap.remove(id);
    }
}
```

**Comment by spericas** [comment] 2023-10-12 15:24
@Neoministein Based on you detailed description, seems like something that should be fixed in Tyrus. If the exception is not caught while attempting to send that closing frame, there's not much Helidon can do. 

Do you agree with this analysis @jansupol?

**Comment by Neoministein** [comment] 2023-10-13 09:53
> @Neoministein Based on your detailed description, seems like something that should be fixed in Tyrus. If the exception is not caught while attempting to send that closing frame, there's not much Helidon can do.

Makes sense. I am not entirely familiar with Helidon's integration with Tyrus that's why I thought it might be possible to fix it on Helidon's side. I'll open an issue on the Tyrus GitHub.

When fixing it in Tyrus. Would the change need to be back merged to 2.0.X or is there a short-term plan already to update Helidon to the Jakarta WebSocket API to version 2.1?

**Comment by spericas** [comment] 2023-10-13 13:24
Helidon 2.x is javax based and Helidon 3.x is jakarta based. It depends how it is fixed in Tyrus. @jansupol is the Tyrus lead and he'll take a look at this shortly.

**Comment by jansupol** [comment] 2023-10-17 19:18
So basically the issue is that `@OnClose` is not invoked. I'll provide a fix to Tyrus.

**Comment by jansupol** [comment] 2023-10-18 12:47
https://github.com/eclipse-ee4j/tyrus/pull/847

**Closed** 2023-10-19 14:31 UTC
Labels: bug, P2, websocket, 4.x
