### ISSUE TITLE
`WebClient` with tracing from CDI extension and `TracingCdiExtension` with Jaeger both initialize OpenTelemetry

### ISSUE THREAD

**Issue by tjquinno** [helidon-io/helidon#5328] opened 2022-11-04 15:56 UTC
[## Environment Details
* Helidon Version: 3.0.2
* Helidon SE or Helidon MP MP
* JDK version:
* OS:
* Docker version (if applicable):

----------

## Problem Description
If a CDI extension uses `WebClient` with tracing to send a request before `TracingCdiExtension` runs, then both try to initialize OpenTelemetry which complains. See the stack trace at the end of the description.

This originally came to light when a user added Jaeger tracing to our MP IDCS example app. The security CDI extension runs before `TracingCdiExtension` and uses the `WebClient`. `WebClient`'s tracing initializes `OpenTelemetry` first, then `TracingCdiExtension` tries to do so again.

## Steps to reproduce
The attached reproducer is an MP QuickStart app enhanced with a CDI extension which uses `WebClient` to contact helidon.io before `TracingCdiExtension` runs. It also has an additional endpoint `/greet/fwd/{name}` which uses `WebClient` to contact the server again at `/greet/{name}`.

Build and run the project
```
mvn package
java -jar target/quickstart-mp.jar
```
and it works, because by default the extension does not use the `WebClient`.

Rerun it to have the extension use the `WebClient`
```
java -DuseExtension -jar target/quickstart-mp.jar
```
and you see the stack trace.

```
Exception in thread "main" java.lang.IllegalStateException: GlobalOpenTelemetry.set has already been called. GlobalOpenTelemetry.set must be called only once before any calls to GlobalOpenTelemetry.get. If you are using the OpenTelemetrySdk, use OpenTelemetrySdkBuilder.buildAndRegisterGlobal instead. Previous invocation set to cause of this exception.
	at io.opentelemetry.api.GlobalOpenTelemetry.set(GlobalOpenTelemetry.java:99)
	at io.helidon.tracing.jaeger.JaegerTracerBuilder.build(JaegerTracerBuilder.java:430)
	at io.helidon.tracing.jaeger.JaegerTracerBuilder.build(JaegerTracerBuilder.java:141)
	at io.helidon.microprofile.tracing.TracingCdiExtension.prepareTracer(TracingCdiExtension.java:74)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:95)
	at org.jboss.weld.injection.MethodInvocationStrategy$SpecialParamPlusBeanManagerStrategy.invoke(MethodInvocationStrategy.java:187)
	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:330)
	at org.jboss.weld.event.ExtensionObserverMethodImpl.sendEvent(ExtensionObserverMethodImpl.java:123)
	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:308)
	at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:286)
	at jakarta.enterprise.inject.spi.ObserverMethod.notify(ObserverMethod.java:125)
	at org.jboss.weld.util.Observers.notify(Observers.java:166)
	at org.jboss.weld.event.ObserverNotifier.notifySyncObservers(ObserverNotifier.java:285)
	at org.jboss.weld.event.ObserverNotifier.notify(ObserverNotifier.java:273)
	at org.jboss.weld.event.EventImpl.fire(EventImpl.java:96)
	at io.helidon.microprofile.cdi.HelidonContainerImpl.doStart(HelidonContainerImpl.java:340)
	at io.helidon.common.context.Contexts.runInContext(Contexts.java:137)
	at io.helidon.microprofile.cdi.HelidonContainerImpl.start(HelidonContainerImpl.java:250)
	at io.helidon.microprofile.cdi.Main.main(Main.java:80)
Caused by: java.lang.Throwable
	at io.opentelemetry.api.GlobalOpenTelemetry.set(GlobalOpenTelemetry.java:107)
	at io.opentelemetry.api.GlobalOpenTelemetry.get(GlobalOpenTelemetry.java:77)
	at io.helidon.tracing.opentelemetry.OpenTelemetryTracerProvider.lambda$static$0(OpenTelemetryTracerProvider.java:62)
	at java.base/java.util.Optional.orElseGet(Optional.java:364)
	at io.helidon.tracing.opentelemetry.OpenTelemetryTracerProvider.lambda$static$1(OpenTelemetryTracerProvider.java:57)
	at io.helidon.common.LazyValueImpl.get(LazyValueImpl.java:118)
	at io.helidon.tracing.opentelemetry.OpenTelemetryTracerProvider.globalTracer(OpenTelemetryTracerProvider.java:84)
	at io.helidon.tracing.jaeger.JaegerTracerProvider.global(JaegerTracerProvider.java:37)
	at io.helidon.tracing.TracerProviderHelper.global(TracerProviderHelper.java:65)
	at io.helidon.tracing.Tracer.global(Tracer.java:40)
	at java.base/java.util.Optional.orElseGet(Optional.java:364)
	at io.helidon.webclient.tracing.WebClientTracing.request(WebClientTracing.java:57)
	at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1187)
	at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2309)
	at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:144)
	at io.helidon.webclient.WebClientRequestBuilderImpl.invoke(WebClientRequestBuilderImpl.java:551)
	at io.helidon.webclient.WebClientRequestBuilderImpl.lambda$request$8(WebClientRequestBuilderImpl.java:415)
	at io.helidon.common.context.Contexts.runInContext(Contexts.java:137)
	at io.helidon.webclient.WebClientRequestBuilderImpl.request(WebClientRequestBuilderImpl.java:415)
	at io.helidon.webclient.WebClientRequestBuilderImpl.submit(WebClientRequestBuilderImpl.java:420)
	at me.test.mp.quickstart.MyExtension.contactHelidon(MyExtension.java:43)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:95)
	at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:85)
	at org.jboss.weld.injection.MethodInvocationStrategy$SimpleMethodInvocationStrategy.invoke(MethodInvocationStrategy.java:168)
	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:330)
	at org.jboss.weld.event.ExtensionObserverMethodImpl.sendEvent(ExtensionObserverMethodImpl.java:123)
	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:308)
	at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:286)
	at jakarta.enterprise.inject.spi.ObserverMethod.notify(ObserverMethod.java:125)
	at org.jboss.weld.util.Observers.notify(Observers.java:166)
	at org.jboss.weld.event.ObserverNotifier.notifySyncObservers(ObserverNotifier.java:285)
	at org.jboss.weld.event.ObserverNotifier.notify(ObserverNotifier.java:273)
	at org.jboss.weld.event.EventImpl.fire(EventImpl.java:96)
	at io.helidon.microprofile.cdi.HelidonContainerImpl.doStart(HelidonContainerImpl.java:296)
	... 3 more
```
[bug.zip](https://github.com/helidon-io/helidon/files/9940057/bug.zip)

**Comment by tomas-langer** [comment] 2022-11-30 10:15
Reproduced

**Comment by tomas-langer** [comment] 2022-11-30 10:19
According to the source code, `TracingCdiExtension.prepareTracer` has higher priority (and should be initialized before) than `SecurityCdiExtension.registerSecurity()`.
Need to reproduce with the original issue to understand the problem.

**Comment by tomas-langer** [comment] 2022-11-30 10:24
The problem is caused by `SecurityCdiExtension.configure` that uses `@Observes @RuntimeStart`, so it is executed long time before tracing is ready.
As we are now refactoring `OidcConfig` (the real cause of this problem, as it initializes WebClient) to support multi tenancy and lazy loading, this issue should be fixed automatically.

We cannot change the order of initialization of tracing, as it needs information from `ServerCdiExtension` that is not available before application scope is initialized.

**Comment by tomas-langer** [comment] 2022-11-30 10:26
Depends on #4383 
Reproducer from this issue will not be fixed - if you use `WebClientTracing` (or `Tracer.global()`) before the `TracingCdiExtension` is executed, you will break tracing, as we cannot prepare the tracer according to Helidon needs.

**Comment by martin-sladecek** [comment] 2022-12-20 16:27
We can repoduce the same issue, but with `IdcsRoleMapperProviderBase` (same issue seems to be in `IdcsRoleMapperRxProviderBase`) - specifically, `OidcConfig.Builder.build()` is calling `OidcMetadata.Builder.build()`, which in turn is using `WebClient` to access `/.well-known/openid-configuration` endpoint on the server. This all happens when parsing the configuration, before the `TracingCdiExtension`.

**Comment by tomas-langer** [comment] 2022-12-21 12:14
I see. I will try to find a solution that would not break us just because webclient tracing is used.

**Comment by arjav-desai** [comment] 2023-01-19 20:54
One of the user mentioned that 

```
It looks like since we are using Jaeger instead of the built in Helidon MP tracing, we actually disable the tracing slightly differently...

> tracing:
>     service: ${app.name}
>     protocol: http
>     host: localhost
>     enabled: false

Doing this allows us to temporarily work around the issue
```

**Closed** 2023-01-29 13:44 UTC
Labels: bug, tracing, P1, webclient, 3.x
