### ISSUE TITLE
even though appropriate tracer object is created and registered globally, calling io.helidon.tracing.Tracer.global() results in DefaultTracer

### ISSUE THREAD

**Issue by AshokVardhanM** [helidon-io/helidon#9486] opened 2024-11-12 12:46 UTC
Even though appropriate tracer object is created and registered globally, calling io.helidon.tracing.Tracer.global() results in DefaultTracer

 We have observed that OpenTelemetryProducer.java's init() method is being executed and both opentelemetry and helidon tracing tracer objects are created. Helidon tracing object is also registered globally via OpenTelemetryTracerProvider.java but when we try to call io.helidon.tracing.Tracer.global() it results in DefaultTracer object instead of appropriate tracer object.

## Environment Details
* Helidon Version: Helidon version 4.0.11
* Helidon MP
* JDK version: JDK 21
* OS: All
* Docker version (if applicable): NA

----------

## Problem Description
We are getting DefaultTracer object on executing io.helidon.tracing.Tracer.global() even when appropriate tracer object is created and registered globally via OpenTelemetryTracerProvider.java

This problem is continuously happening in the application shared/attached in this ticket.

## Steps to reproduce
Start the application from the main class named "StreamsLongevityMain"
We can debug the flow and observe that OpenTelemetryProducer.java's init() method is executed first and then creates and registers the tracer object and then Tracer.global() results in DefaultTracer object.

**Comment by tjquinno** [comment] 2024-11-12 23:45
This might be the same as #9488.

**Comment by tjquinno** [comment] 2024-11-13 14:28
Closing as duplicate of #9488.

**Closed by tjquinno** 2024-11-13 14:28 UTC
