### ISSUE TITLE
Yaml config profiles support

### ISSUE THREAD

**Issue by botsteve** [helidon-io/helidon#5159] opened 2022-10-11 17:34 UTC
## Environment Details
* Helidon MP Version: 3.0.1

I have a question regarding the profile support for yaml config sources. I know there is profile support for microprofile-config-${profile}.properties files but does this support extends also to application-${profile}.yaml files? 

I know that something like this can be done using mp-meta-config file and specify the profile property and an higher ordinal value for application-${profile}  files, thus providing the same functionality as mp.config.profile system property. 

I think that there should be a similar profile support for yaml files using the same system property as for the properties files.

If indeed there is no support for this and it is wanted, i can further pursue this.

**Comment by romain-grecourt** [comment] 2022-10-11 21:08
See https://helidon.io/docs/v3/#/se/config/config-profiles

**Comment by klustria** [comment] 2022-10-17 05:34
Can you please review MP meta-config feature: https://helidon.io/docs/v3/#/mp/config/advanced-configuration#_creating_microprofile_config_sources_from_meta_config and see if that will meet your needs?

**Comment by botsteve** [comment] 2022-10-17 20:23
@klustria yea, this can work as I mentioned above, it is not a problem of making it work using meta-config but more of having a consistent support across different config extensions(.properties, .yaml etc...). Also I think that by having the same system property "mp.config.profile" working using different types of configs will make use of the convention over configuration model, which is desired.

**Comment by klustria** [comment] 2022-10-20 07:23
The problem is that the config source implementation is MP spec based, and that does not have profile anywhere in the SPI. So we do not know which profile to use. The implementation of the [PR](https://github.com/helidon-io/helidon/pull/5163) you created is depending on a system property, which is not the only way to define a profile (it can be defined in another config source). So unless the SPI contains information about which profile to use, we cannot modify it. There might be a way to do this but it may be a little complex than what you PR presents but this may need to be looked at further by the team. In the meantime, your only workaround is to use meta-config.

**Comment by botsteve** [comment] 2022-10-20 08:43
yea, I agree, the problem is the ConfigSourceProvider contract from the MP spec which doesn't provide a profile support, and indeed this doesn't cover the ConfigSource usecase, but I think the general usecase is to cover the system property use.

**Comment by botsteve** [comment] 2022-10-31 13:46
@klustria updated the PR to use reflection to set the profiles property since the MP spec doesn't cover this, this should cover the configuration from other sources besides the system as well.

**Comment by tomas-langer** [comment] 2022-11-03 17:03
Hello @botsteve, this is a limitation of MicroProfile specification and we cannot do much about it. 
We may be able to implement profile based approach for our default "application.yaml" (or any `application.*`) through the existing  spi for `MpMetaConfigProvider` (e.g. if not using meta config, we could create the meta configuration for the supported type and attempt to load it), as that supports profiles correctly.

**Comment by klustria** [comment] 2022-12-01 16:39
This will be fixed by PR https://github.com/helidon-io/helidon/pull/5565 that will have a new SPI (`io.helidon.config.mp.spi.MpConfigSourceProvider`) that extends `org.eclipse.microprofile.config.spi.ConfigSourceProvider` but adds config profile support.

**Comment by klustria** [comment] 2022-12-01 17:14
Closing as https://github.com/helidon-io/helidon/pull/5565 is merged. Will be working to port this into 3.x line.

**Closed by klustria** 2022-12-01 17:14 UTC
Labels: enhancement, config
