### ISSUE TITLE
4.0.5 - Not able to propagate baggage using helidon-tracing-jaeger for active Span

### ISSUE THREAD

**Issue by RickyFrost** [helidon-io/helidon#8504] opened 2024-03-20 21:57 UTC
## Environment Details
* Helidon Version: 4.0.5
* Helidon SE 
* JDK version: 21
* OS: OL7

----------

No longer able to propagate baggage items in 4.0.5 in jaeger provider, was able since 3.2.2

## Problem Description
Identical problem and test case as https://github.com/helidon-io/helidon/issues/7018
I'm able to set and get baggage items locally, but injecting them provides no baggage to server.

## Steps to reproduce
See test in #7018. Identical scenario and outcome.

**Comment by tjquinno** [comment] 2024-03-21 20:53
I cannot reproduce this problem.

Note that propagating the baggage to headers should yield a header with name `baggage` and a value `mykey=myvalue` (with a longer string if more baggage entries had been set). The test in the other issue (as written, at least) searches the headers for `mykey` which will not be there.

I verified the correct behavior by writing a new Jaeger unit test. I plan to create a PR to add the test, but from what I see there is no bug here to fix. 

Side note: when testing Jaeger propagation (or OTel propagation which underlies Jaeger prop) several OTel dependencies need to be present and config settings assigned to avoid gettin a no-op OTel propagator. This will be evident in the test PR!

**Comment by tjquinno** [comment] 2024-03-21 21:23
@RickyFrost I should ask, are you seeing this problem in a running app or just in a test?

**Comment by RickyFrost** [comment] 2024-03-22 16:40
On Helidon 3.x SE code base:
I added the below to the top of my dependency management in pom.xml and tried our tracing regression tests with 3.2.2, 3.2.3, 3.2.4, 3.2.5, and 3.2.6.
-- All work except 3.2.6 which has the same problem as Helidon SE 4.0.5/4.0.6. Hope that helps.

            <dependency>
                <groupId>io.helidon</groupId>
                <artifactId>helidon-bom</artifactId>
                <version>3.2.2</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

**Comment by RickyFrost** [comment] 2024-03-22 16:41
[Helidon-tracing-3.2.5.txt](https://github.com/helidon-io/helidon/files/14725832/Helidon-tracing-3.2.5.txt)

**Comment by RickyFrost** [comment] 2024-03-22 16:41
[Helidon-tracing-3.2.6.txt](https://github.com/helidon-io/helidon/files/14725840/Helidon-tracing-3.2.6.txt)

**Comment by tjquinno** [comment] 2024-03-25 18:27
In a Zoom session Ricky and I saw that the test that fails _activates the span_ before checking the propagation. That's a difference from the test in the older issue and a different in the local test I created.

The propagation does not create the expected headers because the span context that is used to do the propagation does not have baggage, even though the baggage was set.

**Comment by al3xandru** [comment] 2024-03-25 19:42
For tracking purposes and to understand the difference between this and #7018, I'd find it very useful to have an updated code snippet in the description/this thread.

**Comment by RickyFrost** [comment] 2024-03-25 20:27
[BaggagePropagationActiveSpanTest.java.txt](https://github.com/helidon-io/helidon/files/14749212/BaggagePropagationActiveSpanTest.java.txt)

**Closed** 2024-03-27 16:34 UTC
Labels: bug, tracing, P2, 4.x
