### ISSUE TITLE
4.x: oracle.ucp.UniversalConnectionPoolException: All connections in the Universal Connection Pool are in use

### ISSUE THREAD

**Issue by AToMiXhawK** [helidon-io/helidon#8470] opened 2024-03-11 19:33 UTC
## Environment Details
* Helidon Version: 4.x
* Helidon MP
* JDK version: 21
* OS:
* Docker version (if applicable):

----------

## Problem Description
With Helidon 4.x we are facing oracle.ucp.UniversalConnectionPoolException: All connections in the Universal Connection Pool are in use error while trying to persist a list of records in a single transaction with oracle.ucp.jdbc.PoolDataSource.ds.maxPoolSize=10

We are using EclipseLink JPA implementation with Oracle UCP

The same is working with Helidon 3.2.6

## Steps to reproduce
Attaching Helidon 4 and Helidon 3 versions of the same application. On running the PokemonTest.persistPokemonTest test method, it's failing with error with Helidon 4

[quickstart-h3.zip](https://github.com/helidon-io/helidon/files/14563724/quickstart-h3.zip)
[quickstart-h4.zip](https://github.com/helidon-io/helidon/files/14563727/quickstart-h4.zip)

**Comment by ljnelson** [comment] 2024-03-26 22:09
This is not a bug but I understand that JPA's specified behavior can be confusing.

Helidon's JTA transaction handling has improved (become more accurate and correct) from 3 to 4. You may be seeing side effects of this improvement.

When a JTA transaction is active, the flow is like this:

1. A JTA transaction begins.
2. Something in JPA asks a `DataSource` for a connection. (Steps 1 and 2 here may happen in a different order; it doesn't really matter for these purposes.)
3. The connection is enrolled in the transaction. (Its `close()` method is a no-op because the connection should not be returned to the connection pool until the transaction is over.)
4. The connection's `autoCommit` property is set to `false` according to extremely specific rules in the JTA specification. (Users never ever ever ever do this, programmatically or in configuration because otherwise the initial state of the connection will be unknown.)
**Work happens on the connection (`INSERT` statements or whatever)**. (None of these statements commits.)
5. The connection is "closed" (actually the "desire for closing" is recorded but nothing else happens yet, because the connection has not committed its work yet, and it is too soon to do so right now, and if it were actually closed then its work could never commit (or roll back)).
6. The JTA transaction enters its completion phase. (The connection as stated above is still open.)
7. The JTA transaction manager issues a "prepare" command to all enrolled resources. (In this dumb example the connection is the only enrolled resource. There's nothing to "prepare" so it indicates that it is done preparing (basically a no-op).)
8. The JTA transaction manager issues a "commit" command to all enrolled resources. (In this dumb example the connection is the only enrolled resource. The JDBC "commit" operation happens. The work performed in (4) above is committed to the database.)
9. The connection is closed (because the "desire for closing" was recorded earlier in step 5). Because it is a connection from a connection pool (its `DataSource`), the connection is returned to the pool.

During step (4) above, where the actual work happens, let's suppose that the JPA provider has to issue statements to acquire a sequence number from a sequence generator. It has two strategy choices:

S1. It could simply issue those statements as part of the active transaction (i.e. they're just other statements, there's nothing special about them at all; they're just more work performed in step 4).
S2. It could get another connection from the pool and acquire the number that way. (This might or might not involve another transaction; doesn't really matter for these purposes.)

What you're probably seeing is that for _n_ number of `INSERT` statements issued in step 4 (the actual work happening), the JPA provider needs _n_ sequence numbers.  It is probably following step (S2) immediately above, and probably with a new transaction for each such statement, following all the logic above, so you end up with _n_ + 1 connections checked out of the pool (temporarily) while _n_ insertions are happening, since closes (deliberately) do not actually happen and, instead, only "desires for closing" are recorded.

You have many, many, many possible "solutions" to this fully specified but perhaps confusing behavior. Many of them are JPA-provider-specific. In the case of Eclipselink, you could make use of the [`eclipselink.transaction.join-existing`](https://eclipse.dev/eclipselink/documentation/4.0/jpa/extensions/jpa-extensions.html#transactionjoinexisting) property. This tells Eclipselink to follow strategy S1 above. That will cut the number of connections in this dumb example from _n_ + 1 to 1. On the other hand it has caching implications (most JPA developers do not know about all the caching semantics). That may or may not matter to you. There are other Eclipselink properties that affect the way things like sequence number reads happen during transactions.

Another approach that is not guaranteed to work everywhere but that in practice does is to _also_ specify JPA's standard `<non-jta-data-source>` element in your `persistence.xml` (no Eclipselink-specific properties needed), typically pointing at the same database. This allows Eclipselink to follow strategy S2, but to use a different connection pool to acquire these read-only connections. That may or may not be what you want to do. This too has caching implications. (The presence of a `<non-jta-data-source>` element alongside a `<jta-data-source>` element does not obligate a JPA provider to use it, but, as I said, both Eclipselink and Hibernate seem to use it in certain situations.)

**Comment by ljnelson** [comment] 2024-03-26 22:11
Closing since this is not a bug and I've explained how JTA works in this scenario above.

**Closed by ljnelson** 2024-03-26 22:11 UTC
Labels: wontfix
