### ISSUE TITLE
OpenAPI UI returns HTTP 404 status ( but with correct body ) for UI resources when trying to view the UI

### ISSUE THREAD

**Issue by dgeswein-dlx** [helidon-io/helidon#8066] opened 2023-11-22 20:43 UTC
## Environment Details
* Helidon Version: 4.0
* Helidon MP
* JDK version: Oracle Java 21 - java 21.0.1 2023-10-17 LTS Java(TM) SE Runtime Environment (build 21.0.1+12-LTS-29)
* OS: MacOS
* Docker version (if applicable): N/A

----------

## Problem Description
I've built a very basic "Hello World" REST API  using Gradle 8.4 as the build tool.  The REST endpoint I created is working and reachable.  I've included open-api modules per the user guide (including the UI). The generated openapi document is available at the default `/openapi` path.  However, when I try to use the OpenAPI UI, the browser screen is blank.  Checking the network portion of the browser dev consul, I see 404 responses for each of the resources retrieved.  Upon closer inspection, the body of each resource appears to be correct.  The resources are successfully retrieved, but the status code of 404 is preventing correct display.    I have the browser cache disabled.  All configuration of Helidon and OpenAPI feature is default.

As an example, here is the Request/Response details for one of the UI resources:

```
REQUEST:

GET /openapi/ui/index.html HTTP/1.1
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9
Cache-Control: no-cache
Connection: keep-alive
Host: localhost:7001
Pragma: no-cache
Sec-Fetch-Dest: document
Sec-Fetch-Mode: navigate
Sec-Fetch-Site: none
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Safari/605.1.15


RESPONSE (Headers)

HTTP/1.1 404 Not Found
Connection: keep-alive
Content-Length: 2334
Content-Type: text/html
Date: Wed, 22 Nov 2023 11:39:32 -0700

RESPONSE (Body)

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Helidon OpenAPI UI</title>
        <link rel="stylesheet" type="text/css" href="swagger-ui.css" >
        <link rel="stylesheet" type="text/css" href="theme-feeling-blue.css" >

        <link rel="shortcut icon" href="favicon.ico" type="image/x-icon">
        <link rel="icon" href="favicon.ico" type="image/x-icon">
        <link rel="stylesheet" type="text/css" href="style.css" >
    </head>

    <body>
        <div id="swagger-ui"></div>
        <script src="swagger-ui-bundle.js" charset="UTF-8"></script>
        <script src="swagger-ui-standalone-preset.js" charset="UTF-8"> </script>
        <script>
            
            window.onload = 
            
 *****TRUNCATED*****
```

There are no errors or warnings in the logs.  If I downgrade to Helidon MP 3.2.2, then I don't have this issue.

When I run with a debugger, it appears that the `io.helidon.microprofile.server.JaxRsService` class is setting the response status to 404 Not Found.  The request/response is later handled by `io.helidon.webserver.staticcontent.StaticContentHandler` and the response body is successfully sent, but the http status code is still 404 Not Found.

## Steps to reproduce
1. Build the application (see build.gradle file below)
2. Use `./gradlew run` to launch the application

Content of build.gradle:

```
plugins {
    id 'java'
    id 'application'
    id 'org.kordamp.gradle.jandex' version '1.1.0'
}

repositories {
    mavenCentral()
}


mainClassName = 'com.oracle.oa.api.Main'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

run {
    dependsOn('jandex')
}

sourceSets { //Workaround - CDI expects "beans.xml" to be in same directory as classes
    main {
        output.resourcesDir = layout.buildDirectory.dir("classes/java/main").get()
    }
}

dependencies {
    implementation platform("io.helidon:helidon-dependencies:4.0.0")

    implementation 'io.helidon.microprofile.bundles:helidon-microprofile'
    implementation 'io.helidon.logging:helidon-logging-jul'
    implementation 'io.helidon.microprofile.health:helidon-microprofile-health'
    implementation 'io.helidon.microprofile.metrics:helidon-microprofile-metrics'


    runtimeOnly 'io.helidon.microprofile.openapi:helidon-microprofile-openapi'
    runtimeOnly 'io.helidon.integrations.openapi-ui:helidon-integrations-openapi-ui'
    runtimeOnly 'io.smallrye:smallrye-open-api-ui'

    runtimeOnly 'org.jboss:jandex:3.1.2'

    testImplementation platform('org.junit:junit-bom:5.9.1')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

test {
    useJUnitPlatform()
}
```

**Comment by romain-grecourt** [comment] 2023-11-22 20:55
Duplicate of #7913. This will be fixed in 4.0.1

**Closed by romain-grecourt** 2023-11-22 20:55 UTC
Labels: bug, duplicate, MP, open-api, 4.x
