### ISSUE TITLE
Starter strange behavior of Download button

### ISSUE THREAD

**Issue by m0mus** [helidon-io/helidon#6108] opened 2023-02-07 11:59 UTC
It's not a bug, but strange inconsistent behavior. Steps to reproduce:

1. Select Custom application type
2. Media Support default option is JSONP and I can immediately download the zip file.
3. Change Media Support to JSONB. Download button becomes disabled. Why?
4. Press Next and go to the next step. Download button becomes active.
5. Go back to Media Support. Download button is active.

I expect that Download button should not get disabled when I change the Media Support options.

**Comment by romain-grecourt** [comment] 2023-02-07 17:36
This change was implemented after we identified an issue with inconsistent query parameters. FYI you were present when this issue was discussed ;)

This is working as intended: edits must be committed by clicking "next".
If you edit and change a value (either a default value, or a query parameter value) the change requires clicking "next".

Archetypes must be interpreted in order to maintain consistency, however that is expensive and can't be done for every update. We did identify two options:
- interpret on "next"
- interpret on idle (tricky)

We chose to implement the first option, only when there are edits. I.e. if you make an update and then revert it back both the "next" button doesn't show the '!' and the "download" button is clickable.

**Closed by romain-grecourt** 2023-02-07 17:36 UTC
Labels: website
