### ISSUE TITLE
4.x: Upgrade Jersey to 3.1.1

### ISSUE THREAD

**Issue by tomas-langer** [helidon-io/helidon#5821] opened 2023-01-10 11:54 UTC
Upgrade Jersey:

- Upgrade to a version that supports Jakarta 10 (requires #5815)
- Add JAX-RS TCK to our set of TCK tests to make sure Helidon is compliant (if feasible)

**Comment by jbescos** [comment] 2023-02-06 09:11
TCKs are passing when I exclude the tests that deploy war files, and the signature test.

The problem is that these tcks are not published in maven. Jersey is taking them from this URL:
wget -q https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee10/staged/eftl/jakarta-restful-ws-tck-3.1.1.zip -O jakarta-restful-ws-tck-3.1.1.zip

@tomas-langer  question: Do we make TCKs to be published in maven repo, or do I make similar approach than Jersey with a maven plugin?.

**Comment by tomas-langer** [comment] 2023-02-07 13:50
Let's wait for the TCK to be available in Maven central (unless they already are).
For certification purposes, we will add a separate job to use the proper TCK zip file.

**Comment by tomas-langer** [comment] 2023-02-07 13:51
@jbescos could you please upgrade Jersey to 3.1.1?

**Comment by jbescos** [comment] 2023-02-08 07:46
> Let's wait for the TCK to be available in Maven central (unless they already are). For certification purposes, we will add a separate job to use the proper TCK zip file.

I have more information about this topic.

The jars cannot be published in Maven central because of a license issue, and this is not going to be fixed in EE10.

The bundle (the zip file containing the jars) can be published. I guess this is the only option we have right now, unless we want to wait for EE11.

**Closed** 2023-03-14 06:57 UTC
Labels: task, MP, jax-rs, 4.x
