### ISSUE TITLE
4.0.1 websocket WsListener onHttpUpgrade and onOpen use different instance

### ISSUE THREAD

**Issue by baichangda** [helidon-io/helidon#8078] opened 2023-11-28 02:54 UTC
## Environment Details
* Helidon Version: 4.0.1
* Helidon SE
* JDK version: jdk21
* OS: windows

----------

## Problem Description
when use WsRouting.Builder.endpoint(String path, Supplier<WsListener> listener)
the WsListener instance is different in function onHttpUpgrade and onOpen、this is the code screenshot
![image](https://github.com/helidon-io/helidon/assets/24662536/db3467c6-844d-4f6b-8c13-7f9c5c123241)

debug the code i found the WsRoute.listener() will be call twice、maybe it`s the reason
![image](https://github.com/helidon-io/helidon/assets/24662536/84537955-3257-4a51-bf2b-23f6b37a6870)
![image](https://github.com/helidon-io/helidon/assets/24662536/923134b6-b5cf-447d-8dd1-a79cf45529c4)

**Comment by mpenet** [comment] 2023-11-29 18:10
Duplicate of https://github.com/helidon-io/helidon/issues/8039

**Comment by m0mus** [comment] 2023-12-06 17:42
Closing as a duplicate

**Closed by m0mus** 2023-12-06 17:42 UTC
