### ISSUE TITLE
Upgrade logback and slf4j

### ISSUE THREAD

**Issue by RickyFrost** [helidon-io/helidon#8115] opened 2023-12-08 15:10 UTC
The helidon-dependencies-3.2.4.pom for logback is currently 1.2.10. This is out of date and contains unresolved CVE. I suggest the latest jakarta compatible 1.4.14 with no known CVE. Of course slf4j-api will need to advance as well to be compatible, I suggest the latest of 2.0.9.

## Environment Details
* Helidon Version: 3.2.4
* Helidon SE
* JDK version: 17
* OS: Linux
* Docker version (if applicable): n/a

----------

## Problem Description
Require a CVE free version of logback dependency, latest Jakarta-based is 1.4.14. And slf4j will need to advance to a 2.x version to be compatible as well, latest is 2.0.9.

## Steps to reproduce
n/a

**Comment by barchetta** [comment] 2023-12-08 17:30
Duplicate of 7896.

PRs:  #8121 #8119 #8120

**Closed by barchetta** 2023-12-08 17:30 UTC
