### ISSUE TITLE
Intermittent test failure: OciMetricsSupportTest on helidon-2.x at least

### ISSUE THREAD

**Issue by ljnelson** [helidon-io/helidon#4813] opened 2022-08-30 18:39 UTC
On my local machine (MacBook Pro, M1 architecture) occasionally I get this on the `helidon-2.x` branch:
```
org.opentest4j.AssertionFailedError: Timed out after 10 sec. waiting for testMetricCount
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:39)
	at org.junit.jupiter.api.Assertions.fail(Assertions.java:117)
	at io.helidon.integrations.oci.metrics.OciMetricsSupportTest.validateMetricCount(OciMetricsSupportTest.java:271)
	at io.helidon.integrations.oci.metrics.OciMetricsSupportTest.validateMetricCount(OciMetricsSupportTest.java:260)
	at io.helidon.integrations.oci.metrics.OciMetricsSupportTest.testMetricScope(OciMetricsSupportTest.java:158)
```
See also: #4812 which uncovered the issue.

**Comment by klustria** [comment] 2022-09-06 22:48
I ran this in a loop of 200 iterations, and I did see it failed twice:

[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running io.helidon.integrations.oci.metrics.OciMetricsSupportTest
[ERROR] Tests run: 4, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 15.116 s <<< FAILURE! - in io.helidon.integrations.oci.metrics.OciMetricsSupportTest
[ERROR] io.helidon.integrations.oci.metrics.OciMetricsSupportTest.testMetricScope  Time elapsed: 10.028 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: Timed out after 10 sec. waiting for testMetricCount

**Comment by klustria** [comment] 2022-09-07 03:42
The problem has improved tremendously with recent changes after System.nanotime() was used. Prior to this change, it took 33-35 tries, while it took 142 times for the latest version.

**Comment by klustria** [comment] 2022-09-08 18:43
The issue looks like because Metric Registry does not register some of the metrics from the start:


```
Starting OCI Metrics agent
startExecutor with initialDelay: 1 and delay: 20with unit: SECONDS
...
Push Metrics is called with metricDetails size of 0
...
Shutdown is called with counter 1
Shutting down OCI Metrics agent
```

As shown from above, the metricDetails is 0 when it should be greater than that. This happened after the 189th try.

**Comment by klustria** [comment] 2022-09-19 14:47
This issue will be fixed in PR https://github.com/oracle/helidon/pull/4897

**Comment by klustria** [comment] 2022-09-20 16:01
This issue has been tested successfully with over 500 iterations against the changes in https://github.com/helidon-io/helidon/pull/4897. The intermittent issue has not been reproduced anymore.

**Closed by klustria** 2022-09-20 16:01 UTC
Labels: 2.x, intermittent
