### ISSUE TITLE
4.x: WebSocketTest.testMulti test failure

### ISSUE THREAD

**Issue by barchetta** [helidon-io/helidon#4799] opened 2022-08-25 14:38 UTC
I've seen `WebSocketTest.testMulti` fail on the 4.x pipeline.

```
Expected: iterable containing ["First", "Second"]
     but: No item matched: "Second"
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
	at io.helidon.nima.tests.integration.websocket.webserver.WebSocketTest.testMulti(WebSocketTest.java:107)
```

**Comment by barchetta** [comment] 2022-08-25 18:42
We will exclude this test for now until 4.x stabilizes.

**Comment by romain-grecourt** [comment] 2022-09-27 23:40
This test failure occurred again in https://builds.helidon.io/301FB564438323312BFD03FBDDDC00DB

**Comment by spericas** [comment] 2023-10-26 16:37
@barchetta Want to assign it to me?

**Comment by spericas** [comment] 2023-10-30 14:57
> This test failure occurred again in https://builds.helidon.io/301FB564438323312BFD03FBDDDC00DB

@romain-grecourt @barchetta The link above takes me to the list of builds, not the failure. Running the test locally 1000 times does not reproduce the problem.

```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running io.helidon.webserver.tests.websocket.WebSocketTest
[INFO] Tests run: 1000, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 35.498 s - in io.helidon.webserver.tests.websocket.WebSocketTest
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 1000, Failures: 0, Errors: 0, Skipped: 0
```

 Any additional info about how it fails now?

**Comment by romain-grecourt** [comment] 2023-10-30 20:35
> @romain-grecourt @barchetta The link above takes me to the list of builds, not the failure. Running the test locally 1000 times does not reproduce the problem.

We've retired builds.helidon.io it now redirects to GitHub action, so the link is dead :(

We can probably close this and re-open if we see it again.

**Comment by spericas** [comment] 2023-10-31 14:02
Marking it as cannot reproduce and we can reopen later.

**Closed by spericas** 2023-10-31 14:02 UTC
Labels: cannot reproduce, websocket, testing, intermittent, 4.x
