### ISSUE TITLE
[docs] Metrics incorrect menu links

### ISSUE THREAD

**Issue by romain-grecourt** [helidon-io/helidon#4889] opened 2022-09-15 05:30 UTC
Menu links for the following items are not working:

- /mp/metrics/Metrics in HelidonMP
- /mp/metrics/Metrics-Capable Modules
- /se/metrics/Metrics in HelidonMP
- /se/metrics/Metrics-Capable Modules

**Comment by ljamen** [comment] 2022-12-12 19:13
Hi @romain-grecourt I'm not sure what's broken? The menu links at the top of these pages are working for me: 
https://helidon.io/docs/v3/#/mp/metrics/metrics
https://helidon.io/docs/v3/#/mp/metrics/metrics-capable-components
https://helidon.io/docs/v3/#/se/metrics/metrics
https://helidon.io/docs/v3/#/se/metrics/metrics-capable-components

**Comment by barchetta** [comment] 2022-12-13 16:05
@ljamen The links that don't work for me are in the navbar on the left. For example clicking on "Metrics in Helidon MP" does not do anything.

I noticed that  files all start with `metrics-`  and the pages that work do not. So I renamed the MP ones to not start with `metrics-` and they worked! @romain-grecourt I wonder if we have a bug in the tool chain where (waving my hands) if the filename starts with the same word as the directory name the link is broken

**Comment by ljamen** [comment] 2022-12-13 16:20
@barchetta Odd. I'm not able to reproduce this issue. The nav links are also working for me.

**Comment by barchetta** [comment] 2022-12-13 17:36
@ljamen the plot thickens! I see: works in Chrome and Safari. Does not work in Firefox.

**Comment by ljamen** [comment] 2022-12-13 17:49
@barchetta It works in Firefox. That's what I'm using. Bizarre.

**Comment by barchetta** [comment] 2022-12-13 20:55
This is caused by the uBlock Origin ad blocker. See https://github.com/uBlockOrigin/uAssets/issues/15998

**Comment by barchetta** [comment] 2022-12-19 19:39
uBlockOrigin has fixed the issue, therefore I am closing.

**Closed by barchetta** 2022-12-19 19:39 UTC
Labels: bug, docs, 3.x
