### ISSUE TITLE
Kubernetes/docker environment variables are not used in interpolated microprofile-config.properties variables

### ISSUE THREAD

**Issue by jvissers** [helidon-io/helidon#7546] opened 2023-09-07 15:54 UTC
## Environment Details
* Helidon Version: 3.2.2
* Helidon MP
* JDK version: openjdk 17.0.2 2022-01-18
* OS: Linux version 5.4.17-2136.315.5.el7uek.x86_64 (mockbuild @ build-ol7-x86_64.oracle.com)
* Kubernetes version is v1.21.5

----------

## Problem Description
We are experiencing a problem where specific properties in the microprofile-config.properties, cannot successfully be overridden through environment values (passed in through Helm/K8s) as part of other, interpolated properties.

So take the example of these properties in a _microprofile-config.properties_ file

```
oci.outbound-service.streampool-ocid=defaultvalue
kafka.sasl.jaas.config=username="${oci.tenant}/${oci.user}/${oci.outbound-service.streampool-ocid}";
``` 
`
Our deployment works through Helm chart and when specifying the following in _config.dev.yaml_

```
ocioutboundstreampool: alternatevalue
``` 

and in _values.yaml_ has this value:

`
ocioutboundstreampool: oci.outbound-service.streampool-ocid
`

We are seeing that the `kafka.sasl.jaas.config` doesn't get the overridden value specified in Helm. Instead the _defaultvalue_ is used.

However, if we change the value in _values.yaml_ to:

`
ocioutboundstreampool: OCI_OUTBOUND_SERVICE_STREAMPOOL_OCID
`

The value does get overridden, and we see _alternatevalue_

**Comment by jvissers** [comment] 2023-09-07 15:59
Now this might not be relevant, so if not - kindly ignore. But might this be related to the fact that the property that has to be replaced is within double quotes?

**Comment by dalexandrov** [comment] 2023-09-08 14:03
Is there a way you could prove a small reproducer? Locally I try to simulate your situation and everything works fine for me.
Thanks in advance!

**Comment by dalexandrov** [comment] 2023-09-11 13:20
Hm.. let me play with this. Any specific property names, you would like me to test?

**Comment by jvissers** [comment] 2023-09-12 08:03
These are the verbatim properties:

```
oci.outbound-service.endpoint=cell-1.streaming.us-phoenix-1.oci.oraclecloud.com
oci.outbound-service.port=9092
oci.outbound-service.streampool-ocid=ocid1.streampool.oc1.phx.amaaaaaah7afz4ia2v6vrqburhzx7acwvx5oj3syyjmfubydwwsy56rosoeq

kafka.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="${oci.tenant}/${oci.user}/${oci.outbound-service.streampool-ocid}" password="${oci.token}";
```

Then what we try to do is to specify a different value for _oci.outbound-service.streampool-ocid_, by passing an **environment** variable that is specified in Helm values as:

`oci.outbound-service.streampool-ocid=ocid1.streampool.oc1.phx.amaaaaaah7afz4ia4ngyzw2rr4v57e5kmkticstgcuwztq3bjrtt6foozpuq`

**Comment by dalexandrov** [comment] 2023-09-18 13:41
After multiple attempts on MacOS, Linux and other environments we were not able to reproduce the issue. Helidon correctly handles Environmental Variables even with dots. There is also documentation about it https://helidon.io/docs/v3/#/se/config/advanced-configuration

At this moment @jvissers and @dalexandrov agreed to close the issue as "Unable to reproduce".

**Closed by dalexandrov** 2023-09-18 13:41 UTC
Labels: MP, config, 3.x, triage
