### ISSUE TITLE
`@PreDestroy` not called for default scoped JAX-RS Resources 

### ISSUE THREAD

**Issue by barchetta** [helidon-io/helidon#9475] opened 2024-11-07 21:39 UTC
## Environment Details
* Helidon Version: 4.1.3
* Helidon MP
----------

## Problem Description

I don't know if this is a bug or not, but I would to at least like capture the issue and conclusions.

If I have a JAX-RS resource with the default scope (I.e. only `@Path` and no explicit scope annotation), and that resource has 
an `@PreDestroy` method defined, then the PreDestroy method is never called when requests are processed (as it is for `@RequestScoped`) nor is it called at container shutdown (as it is for `@ApplicationScoped`).  This seems wrong.

Related to this is the question: what is Helidon's default scope? Based on experimentation I think it might be `@Dependent`, but I haven't found this documented anywhere.

## Steps to reproduce

Build and run the attached project (which has no scope annotation) 

[custom-mp.zip](https://github.com/user-attachments/files/17669742/custom-mp.zip)

and then exercise it with `curl -X GET http://localhost:8080/simple-greet`. Then terminate it (with ^C). You'll see server output like this:

```
2024.11.07 13:03:46 INFO io.helidon.logging.jul.JulProvider Thread[#1,main,5,main]: Logging at runtime configured using classpath: /logging.properties
CCCCC me.jdipol.mp.custom.SimpleGreetResource@1af1347d: postConstruct
SSSSS me.jdipol.mp.custom.SimpleGreetResource@1af1347d: start
DDDDD me.jdipol.mp.custom.SimpleGreetResource@1af1347d: preDestroy
. . .
CCCCC me.jdipol.mp.custom.SimpleGreetResource@75750d58: postConstruct
CCCCC me.jdipol.mp.custom.SimpleGreetResource@40e95a8f: postConstruct
CCCCC me.jdipol.mp.custom.SimpleGreetResource@48665b57: postConstruct
2024.11.07 13:04:39 INFO io.helidon.Main Thread[#21,helidon-shutdown-thread,5,main]: Shutdown requested by JVM shutting down
2024.11.07 13:04:39 INFO io.helidon.webserver.ServerListener Thread[#45,server-@default-listener,5,main]: [0x51f30ea3] @default socket closed.
2024.11.07 13:04:39 INFO io.helidon.webserver.LoomServer Thread[#21,helidon-shutdown-thread,5,main]: Helidon WebServer stopped all channels.
2024.11.07 13:04:39 INFO io.helidon.microprofile.server.ServerCdiExtension Thread[#21,helidon-shutdown-thread,5,main]: Server stopped in 5 milliseconds.
2024.11.07 13:04:39 INFO io.helidon.Main Thread[#21,helidon-shutdown-thread,5,main]: Shutdown finished
```

So you see the resource getting created, started and destroyed at startup (seems odd, but maybe not wrong). Then `postConstruct` is called for each request.  `preDestroy` is never called which seems wrong.

If you change the resource to use `@ApplicationScoped` and repeat the test you will see:
```
2024.11.07 13:22:50 INFO io.helidon.logging.jul.JulProvider Thread[#1,main,5,main]: Logging at runtime configured using classpath: /logging.properties
CCCCC me.jdipol.mp.custom.SimpleGreetResource@2899a8db: postConstruct
SSSSS me.jdipol.mp.custom.SimpleGreetResource@2899a8db: start
. . .
C2024.11.07 13:23:28 INFO io.helidon.Main Thread[#21,helidon-shutdown-thread,5,main]: Shutdown requested by JVM shutting down
2024.11.07 13:23:28 INFO io.helidon.webserver.ServerListener Thread[#45,server-@default-listener,5,main]: [0x2cf1bf9e] @default socket closed.
2024.11.07 13:23:28 INFO io.helidon.webserver.LoomServer Thread[#21,helidon-shutdown-thread,5,main]: Helidon WebServer stopped all channels.
2024.11.07 13:23:28 INFO io.helidon.microprofile.server.ServerCdiExtension Thread[#21,helidon-shutdown-thread,5,main]: Server stopped in 9 milliseconds.
DDDDD me.jdipol.mp.custom.SimpleGreetResource@2899a8db: preDestroy
2024.11.07 13:23:28 INFO io.helidon.Main Thread[#21,helidon-shutdown-thread,5,main]: Shutdown finished

```

Which seems correct. `postConstruct` is called once at startup.  No lifecycle changes per request. Then `preDestroy` is called once at shutdown.

If you change the resource to use `@RequestScoped` and repeat the test you see:
```
2024.11.07 13:25:14 INFO io.helidon.logging.jul.JulProvider Thread[#1,main,5,main]: Logging at runtime configured using classpath: /logging.properties
. . .
CCCCC me.jdipol.mp.custom.SimpleGreetResource@b653bd0: postConstruct
DDDDD me.jdipol.mp.custom.SimpleGreetResource@b653bd0: preDestroy
CCCCC me.jdipol.mp.custom.SimpleGreetResource@3efde5eb: postConstruct
DDDDD me.jdipol.mp.custom.SimpleGreetResource@3efde5eb: preDestroy
CCCCC me.jdipol.mp.custom.SimpleGreetResource@46f52350: postConstruct
DDDDD me.jdipol.mp.custom.SimpleGreetResource@46f52350: preDestroy
. . .
2024.11.07 13:25:26 INFO io.helidon.Main Thread[#21,helidon-shutdown-thread,5,main]: Shutdown finished
```

Again, this looks correct. No lifecycle changes at startup, and then `postConstruct` and `preDestroy` are called for each request.  And no lifecycle changes at shutdown.

If you repeat the test with `@Dependent` the results are the same as the default scope described at the top of this issue. This seems wrong. I would expect each call to `postConstruct` to have a matching call to `preDestroy`.

**Comment by spericas** [comment] 2024-11-19 14:58
@barchetta I've looked at bean instantiation, and although somewhat unexpected at first, it makes sense how it works. I'm confirming my findings with Jan S. In summary:

1. The first bean instantiation on startup is due to the presence of `void start(@Observes ContainerInitialized event)` in the bean. It needs to be instantiated for the method to be called.
2. The default scope for any CDI bean is dependent. The JAX-RS spec states that resources should instantiated on a _per request_ basis; this requirement existed before CDI was integrated with JAX-RS. Technically, a dependent scope satisfies this need and makes instantiation consistent with the rest of CDI (and likely more efficient than request scope). So request scope must be explicitly set on the bean, is so desired.
3. As to why `@PreDestroy` is not called at all, not even at shutdown is a bit confusing. Maybe this is expected, need to dig into this a bit more.

**Comment by spericas** [comment] 2024-11-22 15:02
Closing because it works as designed

**Closed by spericas** 2024-11-22 15:02 UTC
Labels: bug, jax-rs, P2, cdi, 4.x
