### ISSUE TITLE
Support for Forwarded, X-Forwarded-Host, X-Forwarded-Proto headers

### ISSUE THREAD

**Issue by m0mus** [helidon-io/helidon#7244] opened 2023-07-25 13:09 UTC
Related to #4767

**Comment by dalexandrov** [comment] 2023-08-02 13:35
According to what I saw in the code, this is already done. @tjquinno would you please confirm, and I will close the issue. Thanks!

**Comment by tjquinno** [comment] 2023-08-02 14:19
@dalexandrov As we discussed on Zoom yesterday, if @m0mus can clarify how this issue is different from #4767 that would help. Without that, yes, I believe this is a duplicate of #4767.

**Comment by dalexandrov** [comment] 2023-08-07 07:36
Fixed

**Closed by dalexandrov** 2023-08-07 07:36 UTC
