### ISSUE TITLE
Helidon support in swagger-codegen

### ISSUE THREAD

**Issue by m0mus** [helidon-io/helidon#489] opened 2019-03-08 13:47 UTC
```
$ swagger-codegen langs
Available languages: [aspnetcore, csharp, csharp-dotnet2, dynamic-html, html, html2, java, 
jaxrs-cxf-client, jaxrs-cxf, inflector, jaxrs-cxf-cdi, jaxrs-spec, jaxrs-jersey, jaxrs-di, 
jaxrs-resteasy-eap, jaxrs-resteasy, spring, nodejs-server, openapi, openapi-yaml, 
kotlin-client, kotlin-server, php, python, scala, scala-akka-http-server, swift3, swift4, 
typescript-angular]
```

Would be nice to see Helidon in this list.

**Comment by ProstakovAlexey** [comment] 2019-04-24 11:10
> Would be nice to see Helidon in this list.
Yes it will be really nice. Now API made Helidon look poor, with out swager documentation.

**Comment by longtran84** [comment] 2019-04-27 02:18
@m0mus, can you support me on this issue?

**Comment by tjquinno** [comment] 2019-05-31 14:55
For reference, this page describes how to use and extend the CodeGen tool.

https://swagger.io/docs/open-source-tools/swagger-codegen/

**Comment by tomas-langer** [comment] 2021-06-28 11:41
Isn't this a duplicate of #771 ?

**Comment by tjquinno** [comment] 2021-06-28 12:50
IIRC this issue is for the Swagger tool itself; the other one is for the forked OpenAPI generator.

**Comment by tjquinno** [comment] 2023-01-06 22:29
We have invested time and effort (and plan to continue doing so) into improving the Helidon support in the OpenAPITools generator, rather than the Swagger one. https://github.com/helidon-io/helidon/wiki/FAQ#openapi-based-code-generation

If there is expressed demand for Helidon support in Swagger's offering we can reopen this issue.

**Closed by tjquinno** 2023-01-06 22:29 UTC
Labels: enhancement, MP
