### ISSUE TITLE
4.x: `integrations.cdi.jpa.TestAnnotationRewriting` test failure

### ISSUE THREAD

**Issue by barchetta** [helidon-io/helidon#8122] opened 2023-12-08 19:53 UTC
Test `io.helidon.integrations.cdi.jpa.TestAnnotationRewriting` has started failing on the 4.x validation pipeline. Note that the validation workflow seems to be running slowly at the moment which is triggering timing issues in other tests.  First time I've seen this test fail. It passes when run locally as part of the module build (with other tests) but fails when run in isolation (see @spericas comment below).

```
18:29:01,388 [INFO] Running io.helidon.integrations.cdi.jpa.TestAnnotationRewriting
Error: 3,536 [ERROR] Tests run: 3, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 2.138 s <<< FAILURE! - in io.helidon.integrations.cdi.jpa.TestAnnotationRewriting
Error: 3,537 [ERROR] io.helidon.integrations.cdi.jpa.TestAnnotationRewriting.testNonTransactionalEntityManager  Time elapsed: 0.23 s  <<< ERROR!
org.jboss.weld.exceptions.UnsatisfiedResolutionException: 
WELD-001334: Unsatisfied dependencies for type EntityManager with qualifiers @ContainerManaged @JpaTransactionScoped WELD-001475: The following beans match by type, but none have matching qualifiers:
  - Configurator Bean [class io.helidon.integrations.cdi.jpa.PersistenceExtension, types: JtaExtendedEntityManager, EntityManager, Object, AutoCloseable, DelegatingEntityManager, qualifiers: @Any @Extended @Synchronized @ContainerManaged @Named],
  - Configurator Bean [class io.helidon.integrations.cdi.jpa.PersistenceExtension, types: EntityManager, Object, AutoCloseable, JtaEntityManager, DelegatingEntityManager, qualifiers: @Any @ContainerManaged @JtaTransactionScoped @Synchronized @Named]
  - at org.jboss.weld.bean.builtin.InstanceImpl.checkBeanResolved(InstanceImpl.java:251)
	at org.jboss.weld.bean.builtin.InstanceImpl.get(InstanceImpl.java:113)
	at io.helidon.integrations.cdi.jpa.TestAnnotationRewriting.testNonTransactionalEntityManager(TestAnnotationRewriting.java:165)
  ```

**Comment by spericas** [comment] 2023-12-08 21:57
I was able to reproduce the issue locally if I run the test in isolation:

```
(~/Projects/helidon-4/integrations/cdi/jpa-cdi) >> mvn clean test -Dtest=TestAnnotationRewriting

[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running io.helidon.integrations.cdi.jpa.TestAnnotationRewriting
[ERROR] Tests run: 3, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 3.327 s <<< FAILURE! - in io.helidon.integrations.cdi.jpa.TestAnnotationRewriting
[ERROR] io.helidon.integrations.cdi.jpa.TestAnnotationRewriting.testNonTransactionalEntityManager  Time elapsed: 0.245 s  <<< ERROR!
org.jboss.weld.exceptions.UnsatisfiedResolutionException: 
WELD-001334: Unsatisfied dependencies for type EntityManager with qualifiers @ContainerManaged @JpaTransactionScoped WELD-001475: The following beans match by type, but none have matching qualifiers:
  - Configurator Bean [class io.helidon.integrations.cdi.jpa.PersistenceExtension, types: EntityManager, AutoCloseable, DelegatingEntityManager, Object, JtaExtendedEntityManager, qualifiers: @Any @ContainerManaged @Synchronized @Extended @Named],
  - Configurator Bean [class io.helidon.integrations.cdi.jpa.PersistenceExtension, types: EntityManager, AutoCloseable, DelegatingEntityManager, JtaEntityManager, Object, qualifiers: @Any @ContainerManaged @JtaTransactionScoped @Synchronized @Named]

        at org.jboss.weld.bean.builtin.InstanceImpl.checkBeanResolved(InstanceImpl.java:251)
        at org.jboss.weld.bean.builtin.InstanceImpl.get(InstanceImpl.java:113)
        at io.helidon.integrations.cdi.jpa.TestAnnotationRewriting.testNonTransactionalEntityManager(TestAnnotationRewriting.java:165)
```

**Comment by ljnelson** [comment] 2023-12-09 06:59
Assigning myself just so it doesn't get lost later

**Comment by ljnelson** [comment] 2024-01-13 19:04
See also #8235, which smells related, where Weld itself cannot find things out about itself (!!!), but seemingly only in the pipeline (when run with other tests), or locally when only one test is run.

**Comment by ljnelson** [comment] 2024-07-24 19:54
The root cause of this issue was that this test suite, which was written to exercise the `JpaExtension` class, was never amended when the JPA integration was overhauled. #9037 fixes this and will close this issue.

A subsequent issue will remove the coexistence of the "old stuff" and the "new stuff" so that only the "new stuff" will remain, particularly given that there have been no complaints about the "new stuff" for several releases now, proving in the wild that backwards compatibility in behavior has been achieved.

Regarding how this test could have passed in the first place: my guess is JUnit test ordering.

**Closed** 2024-07-24 21:32 UTC
Labels: bug, MP, P2, cdi, jpa/jta, testing, java, 4.x
